### PR TITLE
Replace has_git by test_requires_git

### PR DESCRIPTION
**Pull request by book**
Test::Git::has_git is obsolete and replaced by
Test::Requires::Git::test_requires_git.

### CODE REVIEW

**Comment by guillaumeaubert** [comment]
@book - The pull request passes all the unit tests, but fails one of the author tests as `Test::Requires::Git` relies on the environment (https://github.com/book/Test-Requires-Git/blob/master/lib/Test/Requires/Git.pm#L78) and `xt/module_versions.t` runs with -T:

```
$ prove xt/module_versions.t
xt/module_versions.t .. 1/5
    #   Failed test 'use App::GitHooks::Test;'
    #   at /home/guillaume/perl5/lib/perl5/Test/Dist/VersionSync.pm line 120.
    #     Tried to use 'App::GitHooks::Test'.
    #     Error:  Insecure $ENV{PATH} while running with -T switch at /home/guillaume/perl5/lib/perl5/Test/Requires/Git.pm line 78.
    # BEGIN failed--compilation aborted at /home/guillaume/cpan/App-GitHooks/lib/App/GitHooks/Test.pm line 20.
    # Compilation failed in require at /home/guillaume/perl5/lib/perl5/Test/Dist/VersionSync.pm line 120.
    # BEGIN failed--compilation aborted at /home/guillaume/perl5/lib/perl5/Test/Dist/VersionSync.pm line 120.

    #   Failed test 'Module App::GitHooks::Test declares a version.'
    #   at /home/guillaume/perl5/lib/perl5/Test/Dist/VersionSync.pm line 123.
    # Looks like you failed 2 tests of 58.
```

Digging deeper into why it's now failing on the `use Test::Requires::Git` in `App::GitHooks::Test`, maybe there should be an option to disable the automatic call to test_requires_git() in `import()` (while leaving it by default, to keep the current API)?

I'm happy to provide a patch, if you think this is a direction in which you want to take `Test::Requires::Git`.

Thank you!

**Comment by book** [comment]
On Thu, Apr 14, 2016 at 08:08:44PM -0700, Guillaume Aubert wrote:
> @book - The pull request passes all the unit tests, but fails one of the author tests as `Test::Requires::Git` relies on the environment (https://github.com/book/Test-Requires-Git/blob/master/lib/Test/Requires/Git.pm#L78) and `xt/module_versions.t` runs with -T:
> 
> ```
> $ prove xt/module_versions.t
> xt/module_versions.t .. 1/5
>     #   Failed test 'use App::GitHooks::Test;'
>     #   at /home/guillaume/perl5/lib/perl5/Test/Dist/VersionSync.pm line 120.
>     #     Tried to use 'App::GitHooks::Test'.
>     #     Error:  Insecure $ENV{PATH} while running with -T switch at /home/guillaume/perl5/lib/perl5/Test/Requires/Git.pm line 78.
>     # BEGIN failed--compilation aborted at /home/guillaume/cpan/App-GitHooks/lib/App/GitHooks/Test.pm line 20.
>     # Compilation failed in require at /home/guillaume/perl5/lib/perl5/Test/Dist/VersionSync.pm line 120.
>     # BEGIN failed--compilation aborted at /home/guillaume/perl5/lib/perl5/Test/Dist/VersionSync.pm line 120.
> 
>     #   Failed test 'Module App::GitHooks::Test declares a version.'
>     #   at /home/guillaume/perl5/lib/perl5/Test/Dist/VersionSync.pm line 123.
>     # Looks like you failed 2 tests of 58.
> ```
> 
> Digging deeper into why it's now failing on the `use Test::Requires::Git` in `App::GitHooks::Test`, maybe there should be an option to disable the automatic call to test_requires_git() in `import()` (while leaving it by default, to keep the current API)?

There is:

    use Test::Requires::Git -nocheck;

-- 
 Philippe Bruhat (BooK)

 We vote to pick our leaders-     /     And we place them in a tower-
 Why is it that we cannot wait-   /     To vote them out of power?
                                (Intro poem to Groo The Wanderer #109 (Epic))

**Comment by guillaumeaubert** [comment]
I should have read the docs more carefully. Thank you, that worked perfectly!

**Comment by book** [comment]
When I realised you didn't see it in the docs, I reorganised them a little so that it would be in a better place.

See f53e85aaf9f1bd4e1f46aa338d888c13f120ecc9.

**Comment by guillaumeaubert** [comment]
Nice! :+1:

**Pull request merged**
